In [6]:
# For Loop
list = []
for i in range (0,10):
    list.append(i*i)
    print(list)





[0]
[0, 1]
[0, 1, 4]
[0, 1, 4, 9]
[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16, 25]
[0, 1, 4, 9, 16, 25, 36]
[0, 1, 4, 9, 16, 25, 36, 49]
[0, 1, 4, 9, 16, 25, 36, 49, 64]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [7]:
# List Comprehnsion
# Variable = [expression for count in range(x1,x2)]

square = [i*i for i in range(0,10)]
square



[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [8]:
odd = [i%2 == 1 for i in range (0,10)]
odd


[False, True, False, True, False, True, False, True, False, True]

In [9]:
square = [i**2 for i in range (0,10)]
square


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [12]:
list = ['Aniket','Parag','Tanvi','Ajay','Nikhil','Mihir']
new_list = [list.upper() for list in list ]
new_list


['ANIKET', 'PARAG', 'TANVI', 'AJAY', 'NIKHIL', 'MIHIR']

In [13]:
new_list = [list.lower() for list in list]
new_list


['aniket', 'parag', 'tanvi', 'ajay', 'nikhil', 'mihir']

In [14]:
new_list = [len(list)for list in list]
new_list


[6, 5, 5, 4, 6, 5]

In [15]:
new_list = (sum([len (list)for list in list]))
new_list

31

In [16]:
new_list = (max([len (list)for list in list]))
new_list

6

In [17]:
new_list = (min([len (list)for list in list]))
new_list

4

In [20]:
# logic: 0 2 4 6 8 : sum : 20
n = sum([x for x in range(0,10)if x % 2 == 0])
n 





20

In [21]:
# logic : 1 3 5 7 9 : sum : 25
n = sum([x for x in range(0,10)if x % 2 != 0])
n

25

In [22]:
# 5! = 5*4*3*2*1 ---> 120
import math
math.factorial(5)


120

In [24]:
# Square Root 
print(5**0.5)
print(math.sqrt(5))


2.23606797749979
2.23606797749979


In [23]:
math.pow(2,2)


4.0

In [25]:
print (math.log10(5))

0.6989700043360189


In [ ]:
# import math
# import os
# import datetime



In [ ]:
# Define Function
def sum():  # sum() function defination
    print('Hello World')
ans = sum() # sum () function calling and storing in variable ans

Hello World


In [10]:
def sum(num1,num2):
    num3 = num1 + num2
    print (f'The addition of two numbers {num1}and {num2} is ',num3)
    return num3

ans = sum(100,200)
# we use fuction for reuseablity


The addition of two numbers 100and 200 is  300


In [ ]:
num1 = float(input('Enter first number:'))
num2 = float(input('Enter the second number:'))

def sum(num1,num2):
    num3 = num1 + num2
    print(f'The addition of two numbers {num1}and {num2} is ',num3)
    

In [13]:
def mul(num1,num2):
    num3 = num1 * num2
    print(f'The mulitplication of two numbers {num1}and {num2} is ',num3)
    return num3
addition = sum(num1,num2)
multiplication = mul(num1,num2)



The addition of two numbers 10.0and 20.0 is  30.0
The mulitplication of two numbers 10.0and 20.0 is  200.0


In [14]:
addition 

30.0

In [15]:
multiplication

200.0

In [20]:
text = input('Enter the String')
text1 = text[::-1]

def  pal(text):
    if text == text1:
        print ('The give string is Palindrom')
    else:
        print('The give string is  not a Palindrom')
    

pal(text)



The give string is Palindrom


In [1]:
'''
balance = 10000
withdraw = Ask User
Theshold balance = 2000

 create function def transation 

'''
balance =10000
threshold = 2000
withdraw = float(input('Ask User: '))

if withdraw >= balance:
    print('Insufficient Balance')
else:
    new_balance = balance - withdraw
    if new_balance >= threshold:
        print('User Current Balance is', new_balance)
    else:
        print('def transation')
        

User Current Balance is 2000.0


In [6]:
'''
CGPA >=  8 : Bright 
CGPA betwwen 6.9 to 7.9 : Moderate Student 
CGPA < 6.8 : Week Student 
''' 
GPA = float(input('Enter CGPA: '))

def compute(CGPA):
    if CGPA >= 8:
        print("Bright Student") 
    elif 6.9 <= CGPA <= 7.9:
        print("Moderate Student")
    else:
        print("Weak Student")
        compute (CGPA) 


In [3]:
text = input('Enter the Text:')

text = text[::-1]

def palindrom(text):
    text1 = text[::-1]
    if text == text1:
        print('The given string is palindrom.')
    else:
        print('The given string is not a palindrom')

palindrom(text)  #calling a function
                 # Palindrom = Reading the word from right or left and left to right.     

The given string is palindrom.


In [9]:
# Recurssive Function
# 5! = 5*4*3*2*1 = 120
def factorial (n):
    if n == 0 or n == 1:
        return 1 # base case
    else:
        return n * factorial(n-1)
    
factorial(5)


120

In [18]:
# OOP : OBJECT ORIENTED PROGRAMMING 
class ClassName:
    i = 12345


x = ClassName ()
x.i



12345

In [21]:
class Complex:
    def __init__(self,real,img): # Constructor Method
        self.r = real # Attribute
        self. i = img # Attribute
x = Complex(10,10)  # x is an object of class complex
x.r  # Calling Attribute using Dot Operator with the help of object x
x.i # # Calling Attribute using Dot Operator with the help of object x

print(x.r,'+',x.i,'j')



10 + 10 j


In [32]:
class addition :
    def __init__(self):
        self. num1 = 100
        self . num2 = 200
    def  sum(self):
        num3 = self.num1 + self.num2
        return num3
a = addition()
a.sum()


300

In [35]:
'''
balance = 10000
withdraw = Ask User
Theshold balance = 2000
''' 
class Bank :
    def __init__(self): 
        self. num1 = float(input('Enter the withdraw amount :'))
if withdraw >= balance:
    print('Insufficient Balance')
else:
    new_balance = balance - withdraw
    if new_balance >= threshold:
        print('User Current Balance is', new_balance)
    else:
        print('def transation')
        
    a = Bank ()
a.sum()
    
    

NameError: name 'withdraw' is not defined

In [3]:
# Parent Class
class Car: 
    def __init__(brand,model):
        brand = brand
        model = model

    def start(self):
        print(f" {self.brand} {self.model}is starting...")

    def stop(self):
        print(f" {self.brand} {self.model}is stopping....")


In [14]:
# Child Class 
class ElecltricCar (Car):
    def __init__(self, brand, model,battery_capacity):
        super().__init__(brand,model)    # Inherit brand and model 
        .battery_capacity = battery_capacity
    def charge(self):
        print(f" {self.brand} {self.model}is charging  with {self.battery_capacity}kWh battery.")
        
# Create an object of ElectricCar
tesla = ElecltricCar("tesla","Model S",10000)
tesla.start()
tesla.charge()
tesla.stop()


 tesla Model Sis starting...
 tesla Model Sis charging  with 10000kWh battery.
 tesla Model Sis stopping....


In [ ]:
class PetrolCar (Car):
    def __init__(self, brand, model,Milage):
        super().__init__(brand,model)    # Inherit brand and model 
        self.Milage = Milage
    def charge(self):
        print(f" {self.brand} {self.model}is charging  with {self.Milage}kWh .")
        
# Create an object of PetrolCar
Hodnda = PetrolCar("Hodnda","Model S",20) 
Hodnda.start()
Hodnda.Milage()
Hodnda.stop()

 Hodnda Model Sis starting...


TypeError: 'int' object is not callable

In [9]:
#Parent Class
class Car :
    def start_engine(self):
     print("Starting Engine...")
class ElectricCar(Car):
    def start_engine(self):
        print("Starting slient electric engine...")
# Child Class
class PetrolCar(Car):
    def start_engine(self):
        print("Starting petrol engine with sound...")

In [19]:
object1 = Car() # Object is Defined as Parent Class 
object2 = ElectricCar() # Object is Defined as Child Class
object3 = PetrolCar() # Object is Defined as Child Class

In [21]:
object1.start_engine()

Starting Engine...


In [23]:
object2.start_engine()

Starting slient electric engine...


In [25]:
object3.start_engine()

Starting petrol engine with sound...


In [35]:
 class Bank:
     def __int__(self)
         self.firstname = firstname
         self.lastname = lastname
         self.age = age
         self.gender = gender 
    def detials(self)
        print(f"input(enter the firstname and lastname...")
        print(f"input(enter the age....")
        print(f"input(enter the gender...")
    


     

IndentationError: unindent does not match any outer indentation level (<string>, line 7)

In [ ]:
# Defining Parent Class : Bank Account
class Bank_Account:
    # Definig special method : Constructor Function
    def __init__(self): 
        # Defining attributes inside  Constructor function 
        self.first_name = input('Enter the first_name')
        self.last_name = input('Enter the last_name')
        self.age = int(input('Enter the age'))
        self.sex = input('Enter the sex')
        self.mobile_number = int(input('mobile_number'))
# Defining Method : Details
    def details(self):
        print(f'The first name is {self.first_name}')
        print(f'The last name is {self.last_name}')
        print(f'The age is {self.age}')
        print(f'The sex is {self.sex} ')
        print(f'The mobile number is {self.mobile_number}')
   # Defing Child Class :Saving Account 
class Saving_Acc(Bank_Account):
    # Defining Method :Interest Rate
    def intrest_rate(self):
        return 3
# Defining Child Class : Current Account 
class Current_Acc(Bank_Account):
    def intrest_rate(self):
        return 0

class Pensioner_acc(Bank_Account):
    def intrest_rate(self):
        return 6
      
class NRI_Acc(Bank_Account):
    def intrest_rate(self):
        return 5 
# Defining  Object 
Mihir,Tanvi  = Saving_Acc()
 Hemangi , disha = Current_Acc()
 Parag, Nikihil = Pensioner_acc()
 Ajay , Aniket = NRI_Acc()

In [1]:
Mihir.interest_rate()


NameError: name 'Mihir' is not defined

In [29]:
# Base class
class Bank:
    def _init_(self, account_holder, balance):
        self.account_holder = account_holder
        self.balance = balance

    def account_details(self):
        print(f"\nAccount Holder: {self.account_holder}")
        print(f"Balance: ₹{self.balance}")

    def rate_of_interest(self):
        print("General Bank Account: No specific interest rate.")

# Child classes
class CurrentAccount(Bank):
    def rate_of_interest(self):
        print("Current Account Interest Rate: 0%")

class SavingsAccount(Bank):
    def rate_of_interest(self):
        print("Savings Account Interest Rate: 3.5%")

class PensionAccount(Bank):
    def rate_of_interest(self):
        print("Pension Account Interest Rate: 5%")

class NRIAccount(Bank):
    def rate_of_interest(self):
        print("NRI Account Interest Rate: 4.5%")

# Function to show details
def show_account_info(account):
    account.account_details()
    account.rate_of_interest()

# Function to create account based on user input
def create_account():
    print("Choose Account Type:")
    print("1. Current Account")
    print("2. Savings Account")
    print("3. Pension Account")
    print("4. NRI Account")
    
    choice = input("Enter your choice (1-4): ")
    name = input("Enter account holder name: ")
    balance = float(input("Enter initial balance: "))

    if choice == '1':
        return CurrentAccount(name, balance)
    elif choice == '2':
        return SavingsAccount(name, balance)
    elif choice == '3':
        return PensionAccount(name, balance)
    elif choice == '4':
        return NRIAccount(name, balance)
    else:
        print("Invalid choice. Defaulting to general Bank account.")
        return Bank(name, balance)

# Create and show account
account = create_account()
show_account_info(account)

Choose Account Type:
1. Current Account
2. Savings Account
3. Pension Account
4. NRI Account


Enter your choice (1-4):  tanvi
Enter account holder name:  tanvi
Enter initial balance:  10000


Invalid choice. Defaulting to general Bank account.


TypeError: Bank() takes no arguments

In [ ]:
# Defeinig Parent Class : Transaction
class Transaction:
# Defining Special method : Constructor 
    def __init__(self):
        self.amount_debited = float(input("Enter the amount_debited..."))
        self. amount_credited = float(input("Enter the amount_credited..."))
        self.amount_balance = 1000
        self.amount_no = int(input("Enter the account no ."))


# Defining method Acc_Details
def account_details (self):
    print(f"enter the amount_no {self.account_no}")
    print(f"balance amount {self.amount_balance}" )
    print (f"Enter ")


    
    

In [4]:
# 1D Array
arr = [1,2,3,4,5,]
print(type(arr))

<class 'list'>


In [5]:
arr.append(6)

In [6]:
arr

[1, 2, 3, 4, 5, 6]

In [14]:
#Numpy Array Formation
import numpy as np 
arr = np.array(arr)
print(arr.ndim) # n Dimensions
print(arr.shape)   # Dataset Shape : rows , Columns
print(arr)           #print : Array


1
(6,)
[1 2 3 4 5 6]


In [15]:
# 2D array
arr1 = [[1,2,3],[4,5,6]]
arr1 = np.array(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1)


2
(2, 3)
[[1 2 3]
 [4 5 6]]


In [16]:
# 3D Array
arr2 = [[[1,2,3],[4,5,6]]]
arr2 = np.array(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2)


3
(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]


In [18]:
a = np.array([[1,2,3,],[4,5,6],[7,8,9]])
b = np.array([[10,20,30,],[40,50,60],[70,80,90]])
c = a+b
print(c)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [19]:
a = np.array([[1,2,3,],[4,5,6],[7,8,9]])
b = np.array([[10,20,30,],[40,50,60],[70,80,90]])
c = a*b
print(c)

[[ 10  40  90]
 [160 250 360]
 [490 640 810]]


In [20]:
a = np.array([[1,2,3,],[4,5,6],[7,8,9]])
b = np.array([[10,20,30,],[40,50,60],[70,80,90]])
c = a/b
print(c)

[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [21]:
a = np.array([[1,2,3,],[4,5,6],[7,8,9]])
b = np.array([[10,20,30,],[40,50,60],[70,80,90]])
c = a-b
print(c)

[[ -9 -18 -27]
 [-36 -45 -54]
 [-63 -72 -81]]


In [26]:
# Diagonal Matrix 
a = np.array([[1,2,3,],[4,5,6],[7,8,9]])
b = np.array([[10,20,30,],[40,50,60],[70,80,90]])
c = np.eye(3)
d = np.zeros(3)
e = np.ones(3)
z = a + e
print(z)

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [23]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
 e

array([1., 1., 1.])