In [2]:
# For Loop
list = []
for i in range (0,10):
    list.append(i*i)
    print(list)





[0]
[0, 1]
[0, 1, 4]
[0, 1, 4, 9]
[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16, 25]
[0, 1, 4, 9, 16, 25, 36]
[0, 1, 4, 9, 16, 25, 36, 49]
[0, 1, 4, 9, 16, 25, 36, 49, 64]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [3]:
# List Comprehnsion
# Variable = [expression for count in range(x1,x2)]

square = [i*i for i in range(0,10)]
square



[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [4]:
odd = [i%2 == 1 for i in range (0,10)]
odd


[False, True, False, True, False, True, False, True, False, True]

In [5]:
square = [i**2 for i in range (0,10)]
square


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [6]:
list = ['Aniket','Parag','Tanvi','Ajay','Nikhil','Mihir']
new_list = [list.upper() for list in list ]
new_list


['ANIKET', 'PARAG', 'TANVI', 'AJAY', 'NIKHIL', 'MIHIR']

In [7]:
new_list = [list.lower() for list in list]
new_list


['aniket', 'parag', 'tanvi', 'ajay', 'nikhil', 'mihir']

In [8]:
new_list = [len(list)for list in list]
new_list


[6, 5, 5, 4, 6, 5]

In [9]:
new_list = (sum([len (list)for list in list]))
new_list

31

In [10]:
new_list = (max([len (list)for list in list]))
new_list

6

In [11]:
new_list = (min([len (list)for list in list]))
new_list

4

In [12]:
# logic: 0 2 4 6 8 : sum : 20
n = sum([x for x in range(0,10)if x % 2 == 0])
n 





20

In [13]:
# logic : 1 3 5 7 9 : sum : 25
n = sum([x for x in range(0,10)if x % 2 != 0])
n

25

In [14]:
# 5! = 5*4*3*2*1 ---> 120
import math
math.factorial(5)


120

In [15]:
# Square Root 
print(5**0.5)
print(math.sqrt(5))


2.23606797749979
2.23606797749979


In [16]:
math.pow(2,2)


4.0

In [17]:
print (math.log10(5))

0.6989700043360189


In [18]:
# import math
# import os
# import datetime



In [19]:
# Define Function
def sum():  # sum() function defination
    print('Hello World')
ans = sum() # sum () function calling and storing in variable ans

Hello World


In [20]:
def sum(num1,num2):
    num3 = num1 + num2
    print (f'The addition of two numbers {num1}and {num2} is ',num3)
    return num3

ans = sum(100,200)
# we use fuction for reuseablity


The addition of two numbers 100and 200 is  300


In [21]:
num1 = float(input('Enter first number:'))
num2 = float(input('Enter the second number:'))

def sum(num1,num2):
    num3 = num1 + num2
    print(f'The addition of two numbers {num1}and {num2} is ',num3)
    

In [22]:
def mul(num1,num2):
    num3 = num1 * num2
    print(f'The mulitplication of two numbers {num1}and {num2} is ',num3)
    return num3
addition = sum(num1,num2)
multiplication = mul(num1,num2)



The addition of two numbers 20.0and 20.0 is  40.0
The mulitplication of two numbers 20.0and 20.0 is  400.0


In [23]:
addition 

In [24]:
multiplication

400.0

In [25]:
text = input('Enter the String')
text1 = text[::-1]

def  pal(text):
    if text == text1:
        print ('The give string is Palindrom')
    else:
        print('The give string is  not a Palindrom')
    

pal(text)



The give string is  not a Palindrom


In [26]:
'''
balance = 10000
withdraw = Ask User
Theshold balance = 2000

 create function def transation 

'''
balance =10000
threshold = 2000
withdraw = float(input('Ask User: '))

if withdraw >= balance:
    print('Insufficient Balance')
else:
    new_balance = balance - withdraw
    if new_balance >= threshold:
        print('User Current Balance is', new_balance)
    else:
        print('def transation')
        

User Current Balance is 9988.0


In [27]:
'''
CGPA >=  8 : Bright 
CGPA betwwen 6.9 to 7.9 : Moderate Student 
CGPA < 6.8 : Week Student 
''' 
GPA = float(input('Enter CGPA: '))

def compute(CGPA):
    if CGPA >= 8:
        print("Bright Student") 
    elif 6.9 <= CGPA <= 7.9:
        print("Moderate Student")
    else:
        print("Weak Student")
        compute (CGPA) 


In [28]:
text = input('Enter the Text:')

text = text[::-1]

def palindrom(text):
    text1 = text[::-1]
    if text == text1:
        print('The given string is palindrom.')
    else:
        print('The given string is not a palindrom')

palindrom(text)  #calling a function
                 # Palindrom = Reading the word from right or left and left to right.     

The given string is palindrom.


In [29]:
# Recurssive Function
# 5! = 5*4*3*2*1 = 120
def factorial (n):
    if n == 0 or n == 1:
        return 1 # base case
    else:
        return n * factorial(n-1)
    
factorial(5)


120

In [30]:
# OOP : OBJECT ORIENTED PROGRAMMING 
class ClassName:
    i = 12345


x = ClassName ()
x.i



12345

In [31]:
class Complex:
    def __init__(self,real,img): # Constructor Method
        self.r = real # Attribute
        self. i = img # Attribute
x = Complex(10,10)  # x is an object of class complex
x.r  # Calling Attribute using Dot Operator with the help of object x
x.i # # Calling Attribute using Dot Operator with the help of object x

print(x.r,'+',x.i,'j')



10 + 10 j


In [32]:
class addition :
    def __init__(self):
        self. num1 = 100
        self . num2 = 200
    def  sum(self):
        num3 = self.num1 + self.num2
        return num3
a = addition()
a.sum()


300

In [33]:
'''
balance = 10000
withdraw = Ask User
Theshold balance = 2000
''' 
class Bank :
    def __init__(self): 
        self. num1 = float(input('Enter the withdraw amount :'))
if withdraw >= balance:
    print('Insufficient Balance')
else:
    new_balance = balance - withdraw
    if new_balance >= threshold:
        print('User Current Balance is', new_balance)
    else:
        print('def transation')
        
    a = Bank ()
a.sum()
    
    

User Current Balance is 9988.0


ValueError: could not convert string to float: ''

In [ ]:
# Parent Class
class Car: 
    def __init__(brand,model):
        brand = brand
        model = model

    def start(self):
        print(f" {self.brand} {self.model}is starting...")

    def stop(self):
        print(f" {self.brand} {self.model}is stopping....")


In [ ]:
# Child Class 
class ElecltricCar (Car):
    def __init__(self, brand, model,battery_capacity):
        super().__init__(brand,model)    # Inherit brand and model 
        .battery_capacity = battery_capacity
    def charge(self):
        print(f" {self.brand} {self.model}is charging  with {self.battery_capacity}kWh battery.")
        
# Create an object of ElectricCar
tesla = ElecltricCar("tesla","Model S",10000)
tesla.start()
tesla.charge()
tesla.stop()


 tesla Model Sis starting...
 tesla Model Sis charging  with 10000kWh battery.
 tesla Model Sis stopping....


In [ ]:
class PetrolCar (Car):
    def __init__(self, brand, model,Milage):
        super().__init__(brand,model)    # Inherit brand and model 
        self.Milage = Milage
    def charge(self):
        print(f" {self.brand} {self.model}is charging  with {self.Milage}kWh .")
        
# Create an object of PetrolCar
Hodnda = PetrolCar("Hodnda","Model S",20) 
Hodnda.start()
Hodnda.Milage()
Hodnda.stop()

 Hodnda Model Sis starting...


TypeError: 'int' object is not callable

In [ ]:
#Parent Class
class Car :
    def start_engine(self):
     print("Starting Engine...")
class ElectricCar(Car):
    def start_engine(self):
        print("Starting slient electric engine...")
# Child Class
class PetrolCar(Car):
    def start_engine(self):
        print("Starting petrol engine with sound...")

In [ ]:
object1 = Car() # Object is Defined as Parent Class 
object2 = ElectricCar() # Object is Defined as Child Class
object3 = PetrolCar() # Object is Defined as Child Class

In [ ]:
object1.start_engine()

Starting Engine...


In [ ]:
object2.start_engine()

Starting slient electric engine...


In [ ]:
object3.start_engine()

Starting petrol engine with sound...


In [ ]:
 class Bank:
     def __int__(self)
         self.firstname = firstname
         self.lastname = lastname
         self.age = age
         self.gender = gender 
    def detials(self)
        print(f"input(enter the firstname and lastname...")
        print(f"input(enter the age....")
        print(f"input(enter the gender...")
    


     

IndentationError: unindent does not match any outer indentation level (<string>, line 7)

In [ ]:
# Defining Parent Class : Bank Account
class Bank_Account:
    # Definig special method : Constructor Function
    def __init__(self): 
        # Defining attributes inside  Constructor function 
        self.first_name = input('Enter the first_name')
        self.last_name = input('Enter the last_name')
        self.age = int(input('Enter the age'))
        self.sex = input('Enter the sex')
        self.mobile_number = int(input('mobile_number'))
# Defining Method : Details
    def details(self):
        print(f'The first name is {self.first_name}')
        print(f'The last name is {self.last_name}')
        print(f'The age is {self.age}')
        print(f'The sex is {self.sex} ')
        print(f'The mobile number is {self.mobile_number}')
   # Defing Child Class :Saving Account 
class Saving_Acc(Bank_Account):
    # Defining Method :Interest Rate
    def intrest_rate(self):
        return 3
# Defining Child Class : Current Account 
class Current_Acc(Bank_Account):
    def intrest_rate(self):
        return 0

class Pensioner_acc(Bank_Account):
    def intrest_rate(self):
        return 6
      
class NRI_Acc(Bank_Account):
    def intrest_rate(self):
        return 5 
# Defining  Object 
Mihir,Tanvi  = Saving_Acc()
 Hemangi , disha = Current_Acc()
 Parag, Nikihil = Pensioner_acc()
 Ajay , Aniket = NRI_Acc()

In [ ]:
Mihir.interest_rate()


NameError: name 'Mihir' is not defined

In [ ]:
# Base class
class Bank:
    def _init_(self, account_holder, balance):
        self.account_holder = account_holder
        self.balance = balance

    def account_details(self):
        print(f"\nAccount Holder: {self.account_holder}")
        print(f"Balance: ₹{self.balance}")

    def rate_of_interest(self):
        print("General Bank Account: No specific interest rate.")

# Child classes
class CurrentAccount(Bank):
    def rate_of_interest(self):
        print("Current Account Interest Rate: 0%")

class SavingsAccount(Bank):
    def rate_of_interest(self):
        print("Savings Account Interest Rate: 3.5%")

class PensionAccount(Bank):
    def rate_of_interest(self):
        print("Pension Account Interest Rate: 5%")

class NRIAccount(Bank):
    def rate_of_interest(self):
        print("NRI Account Interest Rate: 4.5%")

# Function to show details
def show_account_info(account):
    account.account_details()
    account.rate_of_interest()

# Function to create account based on user input
def create_account():
    print("Choose Account Type:")
    print("1. Current Account")
    print("2. Savings Account")
    print("3. Pension Account")
    print("4. NRI Account")
    
    choice = input("Enter your choice (1-4): ")
    name = input("Enter account holder name: ")
    balance = float(input("Enter initial balance: "))

    if choice == '1':
        return CurrentAccount(name, balance)
    elif choice == '2':
        return SavingsAccount(name, balance)
    elif choice == '3':
        return PensionAccount(name, balance)
    elif choice == '4':
        return NRIAccount(name, balance)
    else:
        print("Invalid choice. Defaulting to general Bank account.")
        return Bank(name, balance)

# Create and show account
account = create_account()
show_account_info(account)

Choose Account Type:
1. Current Account
2. Savings Account
3. Pension Account
4. NRI Account


Enter your choice (1-4):  tanvi
Enter account holder name:  tanvi
Enter initial balance:  10000


Invalid choice. Defaulting to general Bank account.


TypeError: Bank() takes no arguments

In [ ]:
# Defeinig Parent Class : Transaction
class Transaction:
# Defining Special method : Constructor 
    def __init__(self):
        self.amount_debited = float(input("Enter the amount_debited..."))
        self. amount_credited = float(input("Enter the amount_credited..."))
        self.amount_balance = 1000
        self.amount_no = int(input("Enter the account no ."))


# Defining method Acc_Details
def account_details (self):
    print(f"enter the amount_no {self.account_no}")
    print(f"balance amount {self.amount_balance}" )
    print (f"Enter ")


    
    

In [36]:
# 1D Array
arr = [1,2,3,4,5,]
print(type(arr))

<class 'list'>


In [37]:
arr.append(6)

In [38]:
arr

[1, 2, 3, 4, 5, 6]

In [39]:
#Numpy Array Formation
import numpy as np 
arr = np.array(arr)
print(arr.ndim) # n Dimensions
print(arr.shape)   # Dataset Shape : rows , Columns
print(arr)           #print : Array


1
(6,)
[1 2 3 4 5 6]


In [40]:
# 2D array
arr1 = [[1,2,3],[4,5,6]]
arr1 = np.array(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1)


2
(2, 3)
[[1 2 3]
 [4 5 6]]


In [41]:
# 3D Array
arr2 = [[[1,2,3],[4,5,6]]]
arr2 = np.array(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2)


3
(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]


In [42]:
a = np.array([[1,2,3,],[4,5,6],[7,8,9]])
b = np.array([[10,20,30,],[40,50,60],[70,80,90]])
c = a+b
print(c)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [43]:
a = np.array([[1,2,3,],[4,5,6],[7,8,9]])
b = np.array([[10,20,30,],[40,50,60],[70,80,90]])
c = a*b
print(c)

[[ 10  40  90]
 [160 250 360]
 [490 640 810]]


In [44]:
a = np.array([[1,2,3,],[4,5,6],[7,8,9]])
b = np.array([[10,20,30,],[40,50,60],[70,80,90]])
c = a/b
print(c)

[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [45]:
a = np.array([[1,2,3,],[4,5,6],[7,8,9]])
b = np.array([[10,20,30,],[40,50,60],[70,80,90]])
c = a-b
print(c)

[[ -9 -18 -27]
 [-36 -45 -54]
 [-63 -72 -81]]


In [ ]:
# Diagonal Matrix 
a = np.array([[1,2,3,],[4,5,6],[7,8,9]])
b = np.array([[10,20,30,],[40,50,60],[70,80,90]])
c = np.eye(3) # Identity Matrix
d = np.zeros(3) # Array of All Zeros
e = np.ones(3) # Array of All Ones
z = a +e
print(z)

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [47]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
 e

array([1., 1., 1.])

In [49]:
a/2 


array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [50]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [52]:
a *[2,3,4]


array([[ 2,  6, 12],
       [ 8, 15, 24],
       [14, 24, 36]])

In [51]:
a *[[1,2,3],[4,2,5],[5,6,1]]

array([[ 1,  4,  9],
       [16, 10, 30],
       [35, 48,  9]])

In [53]:
# Changing Dtype : Datatype
a = np.array([1,2,3],dtype = 'float')
a 

array([1., 2., 3.])

In [54]:
# Changing Dtype : Datatype
a = np.array([1,2,3],dtype = 'bool')
a 

array([ True,  True,  True])

In [55]:
# Changing Dtype : Datatype
a = np.array([1,2,3],dtype = 'complex')
a 

array([1.+0.j, 2.+0.j, 3.+0.j])

In [56]:
# Arrange Function 
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
 #Arrange Function 
# np.arange (start,stop,step)
# str (start:stop:stop)
a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [58]:
num = np.arange(0,20)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [59]:
num.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [60]:
# 5 rows , 4 columns

num.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [61]:
num.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [62]:
num.reshape(1,1,20)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19]]])

In [63]:
np.linspace(1,10,8)

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [64]:
 a = np.linspace(0,20,10)
print(a.size)
a 

10


array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [65]:
num = np.arange(0,30)
num 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [68]:
# m:5 :---> no. of rows and n:6---> no.of columns
arr = num.reshape(5,6)
arr 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [69]:
# Aggeragate Function 
arr.max(), arr.min(), arr.mean(),arr.std()

(29, 0, 14.5, 8.65544144839919)

In [70]:
# what is difference between np.arange & np.linspace
# ans = arange is arranh=ge in sqience 
# linspace is 


In [ ]:
# stdevations is underroot of varience 
# varience is spread of data distance between with respect to between the mean 
# idel stdard devations is = 1


In [ ]:
# Compute the by column wise
arr.sum(axis= 1)



array([ 15,  51,  87, 123, 159])

In [72]:
arr.sum(axis= 0)

array([60, 65, 70, 75, 80, 85])

In [ ]:
#arr[:,:] # 1st : is for coloumn & 2nd : is for rows


In [73]:
arr[1:4,2:5]

array([[ 8,  9, 10],
       [14, 15, 16],
       [20, 21, 22]])

In [89]:
arr[1:4]

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [92]:
n = np.arange(50,100)# 1D
m = n.reshape(10,5) # 2D
print(m.ndim) # CHECKING DEMINAISION : 2D
m[1:3,1:3]
m

2


array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [93]:
m[6:9,1:4]

array([[81, 82, 83],
       [86, 87, 88],
       [91, 92, 93]])

In [132]:
n = np.arange(101,131 ,dtype ='float')
m = n.reshape (1,5,6)
n

array([101., 102., 103., 104., 105., 106., 107., 108., 109., 110., 111.,
       112., 113., 114., 115., 116., 117., 118., 119., 120., 121., 122.,
       123., 124., 125., 126., 127., 128., 129., 130.])

In [ ]:
# Numpy will not entertain categorical column 

In [ ]:
# Exporlatary data anlaysis is classified in 2 
# 1) univaraite analysis 
